// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA06s-8uZXf0Zc8PMUhkwFGOeThNCv9tQc',
    appId: '1:91456020647:web:1f99a78765d7eb8a73bb82',
    messagingSenderId: '91456020647',
    projectId: 'ontime-9c2c1',
    authDomain: 'ontime-9c2c1.firebaseapp.com',
    storageBucket: 'ontime-9c2c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCazhDa38F5uDcoa3I6WYt4_DXNs7pjMGc',
    appId: '1:91456020647:ios:93e0ff0b7558935573bb82',
    messagingSenderId: '91456020647',
    projectId: 'ontime-9c2c1',
    storageBucket: 'ontime-9c2c1.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCazhDa38F5uDcoa3I6WYt4_DXNs7pjMGc',
    appId: '1:91456020647:ios:93e0ff0b7558935573bb82',
    messagingSenderId: '91456020647',
    projectId: 'ontime-9c2c1',
    storageBucket: 'ontime-9c2c1.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA06s-8uZXf0Zc8PMUhkwFGOeThNCv9tQc',
    appId: '1:91456020647:web:43f7892d1ed02c9273bb82',
    messagingSenderId: '91456020647',
    projectId: 'ontime-9c2c1',
    authDomain: 'ontime-9c2c1.firebaseapp.com',
    storageBucket: 'ontime-9c2c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNquK02vzGRuuzXjDX_dHaP3qZngJwxt0',
    appId: '1:91456020647:android:1bd2cac19cce046b73bb82',
    messagingSenderId: '91456020647',
    projectId: 'ontime-9c2c1',
    storageBucket: 'ontime-9c2c1.firebasestorage.app',
  );

}